DROP TABLE IF EXISTS CARGA;
CREATE TABLE CARGA(ID BIGINT auto_increment, PRODUCT VARCHAR(255), QUANTITY VARCHAR(255), PRICE VARCHAR(255), TYPE VARCHAR(255), INDUSTRY VARCHAR(255), ORIGIN VARCHAR(255));
DROP TABLE IF EXISTS CARREGADO;
CREATE TABLE CARREGADO(ID BIGINT auto_increment, FILE VARCHAR(255), QUANTITY VARCHAR(255));